name: AuraDB (managed Neo4j)
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * */2
jobs:
  neo4j:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: neo4j
    steps:
      - name: setup dockerode
        uses: davidkhala/setup-dockerode@main
      - run: npm install
      - run: npm run test-aura
        env:
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}