name: neo4j-cloud
on:
  schedule:
    - cron: 0 0 * * */2
jobs:
  aura-db:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: neo4j
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm run test:aura
        env:
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}