on: push
jobs:
  common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ common, mysql, sequelize ]
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: davidkhala/setup-dockerode@main
      - run: npm install
      - run: npm test
        env:
          AIVEN_PASSWORD: ${{ secrets.AIVEN_PASSWORD }}