name: database
on: push
jobs:
  db-nodocker:
    runs-on: ubuntu-latest
    env:
      FAUNA_PASSWORD: ${{ secrets.FAUNA_PASSWORD }}
    strategy:
      matrix:
        db: [ leveldb, fauna ]
    defaults:
      run:
        working-directory: ${{matrix.db}}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm test

  db-dockerode:
    runs-on: ubuntu-latest
    env:
      # for mongodb
      ATLAS_PASSWORD: ${{ secrets.ATLAS_PASSWORD }}
      ADB_PASSWORD: ${{secrets.ADB_PASSWORD}}
      # for tinkerpop
      COSMOS_MONGODB_PASSWORD: ${{ secrets.COSMOS_MONGODB_PASSWORD }}
      COSMOS_GREMLIN_PASSWORD: ${{ secrets.COSMOS_GREMLIN_PASSWORD }}
      # for postgre
      SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
      NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
    strategy:
      matrix:
        db: [ neo4j, postgre/pg,neon, tinkerpop, mongodb ]
    defaults:
      run:
        working-directory: ${{matrix.db}}
    steps:
      - name: setup dockerode
        uses: davidkhala/setup-dockerode@main
      - run: npm install
      - run: npm test
  redis:
    runs-on: ubuntu-latest
    env:
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    defaults:
      run:
        working-directory: redis
    steps:
      # take care of root permission required by dragonFly
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - uses: actions/checkout@main
      - run: npm install
      - run: npm test