name: database
on: push
jobs:
  db-nodocker:
    runs-on: ubuntu-latest
    env:
      FAUNA_PASSWORD: ${{ secrets.FAUNA_PASSWORD }}
    strategy:
      matrix:
        db: [ leveldb, fauna ]
    defaults:
      run:
        working-directory: ${{matrix.db}}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm test

  db-dockerode:
    runs-on: ubuntu-latest
    env:
      # for mongodb
      ADB_PASSWORD: ${{secrets.ADB_PASSWORD}}
      # for tinkerpop
      COSMOS_MONGODB_PASSWORD: ${{ secrets.COSMOS_MONGODB_PASSWORD }}
      COSMOS_GREMLIN_PASSWORD: ${{ secrets.COSMOS_GREMLIN_PASSWORD }}
      # for postgre
      NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
    strategy:
      matrix:
        db: [ neo4j, postgre/pg,neon, tinkerpop, mongodb,mssql, redis]
    defaults:
      run:
        working-directory: ${{matrix.db}}
    steps:
      - uses: davidkhala/setup-dockerode@main
      - run: npm install
      - run: npm test
  Azure-SQL:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mssql
    environment: Azure
    env:
      SQL_PASSWORD: ${{secrets.SQL_PASSWORD}}
      SQL_DOMAIN: ${{vars.SQL_DOMAIN}}
      SQL_USER: ${{vars.SQL_USER}}
    steps:
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - uses: actions/checkout@main
      - run: npm install
      - run: npm run test:azure