name: database
on: push
jobs:
  mongoDB:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mongodb
    steps:
      - name: setup dockerode
        uses: davidkhala/setup-dockerode@main
      - run: npm install
      - run: npm test
        env:
          ATLAS_PASSWORD: ${{ secrets.ATLAS_PASSWORD }}
          COSMOS_MONGODB_PASSWORD: ${{ secrets.COSMOS_MONGODB_PASSWORD }}
  leveldb:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: leveldb
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          check-latest: true
      - run: npm install
      - run: npm test
  redis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: redis
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          check-latest: true
      - run: npm install
      - run: npm test
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  tinkerpop:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tinkerpop
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          check-latest: true
      - uses: ScribeMD/rootless-docker@main
        name: Use Docker in rootless mode.
      - run: npm install
      - run: npm test
        env:
          COSMOS_GREMLIN_PASSWORD: ${{ secrets.COSMOS_GREMLIN_PASSWORD }}
  neo4j:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: neo4j
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          check-latest: true
      - uses: ScribeMD/rootless-docker@main
        name: Use Docker in rootless mode.
      - run: npm install
      - run: npm test
        env:
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
  postgre:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: postgre
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          check-latest: true
      - uses: ScribeMD/rootless-docker@main
        name: Use Docker in rootless mode.
      - run: npm install
      - run: npm test