name: database
on: push
env:
  ATLAS_PASSWORD: ${{ secrets.ATLAS_PASSWORD }}
  COSMOS_MONGODB_PASSWORD: ${{ secrets.COSMOS_MONGODB_PASSWORD }}
  COSMOS_GREMLIN_PASSWORD: ${{ secrets.COSMOS_GREMLIN_PASSWORD }}
  PLANETSCALE_PASSWORD: ${{ secrets.PLANETSCALE_PASSWORD}}
  FAUNA_PASSWORD: ${{ secrets.FAUNA_PASSWORD }}
  SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
  NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
jobs:
  db-nodocker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [ leveldb, fauna ]
    defaults:
      run:
        working-directory: ${{matrix.db}}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm test

  db-dockerode:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [ neo4j, postgre, tinkerpop, mongodb ]
    defaults:
      run:
        working-directory: ${{matrix.db}}
    steps:
      - name: setup dockerode
        uses: davidkhala/setup-dockerode@main
      - run: npm install
      - run: npm test
