on: push
jobs:
  common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ common, sequelize ]
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@main
      - run: npm install
      - run: npm test