name: always-free DBaaS (terminate once stale)
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * */2
env:
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
jobs:
  aura-db:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: neo4j
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm run test-aura
        env:
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
  data-cloud:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: [ redis ]
    defaults:
      run:
        working-directory: ${{matrix.provider}}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm test
