name: always-free DBaaS (terminate once stale)
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * */3
jobs:
  aura-db:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: neo4j
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm run test:aura
        env:
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
  supabase:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: postgre
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm run test:supabase
        env:
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
  redis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: redis
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm test
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
