name: Retain always-free DBaaS
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * */3
  push:
jobs:
  aura-db:
    environment: AURA
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: neo4j
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm run test:aura
        env:
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          INSTANCE: ${{vars.INSTANCE}}
  supabase-pg:
    runs-on: ubuntu-latest
    environment: SUPABASE
    defaults:
      run:
        working-directory: postgre/pg
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm run test:supabase
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          PROJECT: ${{vars.PROJECT}}
  supabase-backend:
    runs-on: ubuntu-latest
    environment: SUPABASE
    defaults:
      run:
        working-directory: supabase
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm test
        env:
          PROJECT: ${{vars.PROJECT}}
          SERVICE_ROLE: ${{secrets.SERVICE_ROLE}}
  redis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deploy: [redis-cloud, render]
    environment: ${{matrix.deploy}}
    defaults:
      run:
        working-directory: redis
    env:
      REDIS_ENDPOINT: ${{ vars.REDIS_ENDPOINT}}
      REDIS_USER : ${{ vars.REDIS_USER }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm run test:${{matrix.deploy}}

  Atlas:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mongodb
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
      - run: npm run test:atlas
        env:
          ATLAS_PASSWORD: ${{ secrets.ATLAS_PASSWORD }}
  Aiven:
    runs-on: ubuntu-latest
    environment: AIVEN
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
        working-directory: mysql
      - run: npm run test:aiven
        working-directory: mysql
        env:
          MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
          MYSQL_HOST: ${{vars.MYSQL_HOST}}
          MYSQL_CA: ${{vars.MYSQL_CA}}