name: sequelize
on: push
jobs:
  mysql:
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: database
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin status -uroot -p$MYSQL_ROOT_PASSWORD" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
      - run: npm install
        working-directory: sequelize/mysql
      - run: npm test
        working-directory: sequelize/mysql
