name: sequelize
on: push
defaults:
  run:
    working-directory: sequelize
jobs:
  sequelize:
    services:
      mysql:
        image: mysql
#       docker run -e MYSQL_DATABASE=database -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 mysql
        env:
          MYSQL_DATABASE: database
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          check-latest: true
      - run: npm install
      - run: npm test
